apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: cicd
    notifications.argoproj.io/subscribe.on-sync-failed.slack: cicd
    notifications.argoproj.io/subscribe.on-sync-running.slack: cicd
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: cicd
    notifications.argoproj.io/subscribe.on-deployed.slack: cicd
    notifications.argoproj.io/subscribe.on-health-degraded.slack: cicd
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web-community
          image: 087600766519.dkr.ecr.ap-northeast-2.amazonaws.com/web:34
          ports:
            - containerPort: 9091